---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: iamra-ca
  namespace: cert-manager
behavior: create
files:
  - tls.crt=../rootCACert.pem
  - tls.key=../rootCAKey.pem
type: kubernetes.io/tls
options:
  disableNameSuffixHash: true