---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # load secret from embedded content
  - ca-issuer.yaml

generators:
  # load secret from file
  - ca-secret-extfile.yaml