---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    app: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          args: ["--verbose"]
          env:
            - name: WHOAMI_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: test

spec:
  selector:
    app: whoami

  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  name: whoami
  namespace: test
  labels:
    app: whoami
spec:
  ingressClassName: traefik
  rules:
  - host: whoami.private.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/issuer: "pca-issuer"
    cert-manager.io/issuer-kind: AWSPCAClusterIssuer
    cert-manager.io/issuer-group: awspca.cert-manager.io
    cert-manager.io/usages: "server auth,client auth"
  name: whoami-tls
  namespace: test
  labels:
    app: whoami
spec:
  ingressClassName: traefik
  rules:
  - host: whoami.private.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              number: 80
  tls:
  - hosts:
    - whoami.private.example.com
    secretName: whoami-tls
    