---
apiVersion: v1
kind: Service
metadata:
  name: aws-signing-helper
spec:
  selector:
    app: aws-signing-helper
  ports:
    - protocol: TCP
      port: 9911
      targetPort: 9911
  type: ClusterIP